### ISSUE TITLE
Not building on mac

### ISSUE THREAD

**Issue by lnikj** [aptrn/aP-Modules#1]
c++ -o plugin.dylib build/src/Buffer.cpp.o build/src/MSMTRX.cpp.o build/src/QuantizeUtils.cpp.o build/src/Template.cpp.o build/src/Tempo.cpp.o build/src/aP.cpp.o build/src/hpMeter.cpp.o  -shared -undefined dynamic_lookup -stdlib=libc++ -mmacosx-version-min=10.7
duplicate symbol _init in:
    build/src/Template.cpp.o
    build/src/aP.cpp.o
duplicate symbol _plugin in:
    build/src/Template.cpp.o
    build/src/aP.cpp.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [plugin.dylib] Error 1

**Comment by davephillips** [comment]
Fedora 23 Linux
Rack 0.6.2b

Similar/same error here:

g++ -o plugin.so build/src/MSMTRX.cpp.o build/src/QuantizeUtils.cpp.o build/src/Tempo.cpp.o build/src/hpMeter.cpp.o build/src/aP.cpp.o build/src/Template.cpp.o build/src/Buffer.cpp.o  -shared
build/src/Template.cpp.o: In function `init':
/home/dlphilp/src/Rack-062/plugins/aP-Modules/src/Template.cpp:7: multiple definition of `init'
build/src/aP.cpp.o:/home/dlphilp/src/Rack-062/plugins/aP-Modules/src/aP.cpp:7: first defined here
build/src/Template.cpp.o: In function `init':
/home/dlphilp/src/Rack-062/plugins/aP-Modules/src/Template.cpp:7: multiple definition of `plugin'
build/src/aP.cpp.o:/home/dlphilp/src/Rack-062/plugins/aP-Modules/src/aP.cpp:7: first defined here
collect2: error: ld returned 1 exit status
../../compile.mk:55: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

**Comment by aptrn** [comment]
It should be fine now, had files that shouldn't be there

**Comment by davephillips** [comment]
All good here now, thanks !

**Comment by lnikj** [comment]
Yep, fixed, many thanks!
