### ISSUE TITLE
image question

### ISSUE THREAD

**Issue by davephillips** [aptrn/aP-Modules#2]
Linux Fedora 23
Rack 0.6.2b from source

Greetings ! No problems with building and loading your modules, but I wondered about the text alignment on some of the labels:

![apmodules](https://user-images.githubusercontent.com/7815938/45917105-80071e00-be3e-11e8-8902-3af1ac2b39cf.png)

Is that what we should see ?

**Comment by aptrn** [comment]
they're fine, new design
many things to fix at the moment, they're not ready yet
